---
- name: Create /usr/local/nginx_templates dir
  file:
    path: /usr/local/nginx_templates
    state: directory
    mode: 0755

- name: Copy nginx templates
  template:
    src: "{{ item }}"
    dest: "/usr/local/nginx_templates/{{ item }}"
  loop: "{{ nginx_conf_d_templates }}"

- name: Run nginx
  docker_container:
    name: nginx
    restart_policy: always
    image: "nginx:{{ nginx_version }}"
    restart: "{{ nginx_restart | default(false) }}"
    volumes:
      - /usr/local/nginx_templates:/etc/nginx/templates
    env: "{{ nginx_environments }}"
    links: "{{ nginx_links | default(omit) }}"
    ports: "{{ nginx_ports | default(omit) }}"
    log_driver: "{{ nginx_log_driver | default(omit) }}"
    log_options: "{{ nginx_log_options | default(omit) }}"
  tags:
    - run-nginx
