---
- name: Converge
  hosts: all

  vars:
    pip_install_packages:
      - name: docker
    molecule_scenario_no_deps: true
    nginx_links:
      - httpd
    nginx_ports:
      - 80:80
  tasks:
    - name: apt update
      apt:
        update_cache: yes

    - import_role:
        name: geerlingguy.pip

    - name: Start httpd
      docker_container:
        name: httpd
        restart_policy: always
        image: httpd:2.4
    - name: "Include ansible-role-docker-nginx"
      include_role:
        name: "ansible-role-docker-nginx"

    - name: Download test localhost
      uri:
        url: http://localhost
        return_content: true
      register: this
      failed_when: "'Welcome to nginx!' not in this.content"
      delegate_to: localhost
      become: false
